# Generated by AheadLibEx (Rust)
# Author: i1tao
# GitHub: https://github.com/i1tao/AheadLibEx

cmake_minimum_required(VERSION 3.20)

project({{CMAKE_PROJECT_NAME}} LANGUAGES C)

# Toolchain selection:
# - MSVC / clang-cl: MASM (.asm)
# - MinGW-w64 (gcc/clang): GAS (.S)
if(MSVC)
  enable_language(ASM_MASM)
else()
  enable_language(ASM)
endif()

set(AHEADLIBEX_BASE "{{BASE}}")
set(AHEADLIBEX_OUTPUT_NAME "{{OUTPUT_NAME}}")
set(AHEADLIBEX_C "{{C_SRC}}")
set(AHEADLIBEX_ASM_MASM "{{ASM_MASM_SRC}}")
set(AHEADLIBEX_ASM_GAS "{{ASM_GAS_SRC}}")
set(AHEADLIBEX_DEF "{{DEF_SRC}}")

if(MSVC)
  set(AHEADLIBEX_ASM "${AHEADLIBEX_ASM_MASM}")
else()
  set(AHEADLIBEX_ASM "${AHEADLIBEX_ASM_GAS}")
endif()

add_library(${PROJECT_NAME} SHARED
  "${CMAKE_CURRENT_LIST_DIR}/${AHEADLIBEX_C}"
  "${CMAKE_CURRENT_LIST_DIR}/${AHEADLIBEX_ASM}"
)

set_target_properties(${PROJECT_NAME} PROPERTIES
  OUTPUT_NAME "${AHEADLIBEX_OUTPUT_NAME}"
  RUNTIME_OUTPUT_NAME "${AHEADLIBEX_OUTPUT_NAME}"
  ARCHIVE_OUTPUT_NAME "${AHEADLIBEX_OUTPUT_NAME}"
  LIBRARY_OUTPUT_NAME "${AHEADLIBEX_OUTPUT_NAME}"
  PREFIX ""
  DEBUG_POSTFIX ""
)

target_include_directories(${PROJECT_NAME} PRIVATE "${CMAKE_CURRENT_LIST_DIR}")
target_link_libraries(${PROJECT_NAME} PRIVATE user32)

# Use .def for exports across toolchains.
if(MSVC)
  target_link_options(${PROJECT_NAME} PRIVATE "/DEF:${CMAKE_CURRENT_LIST_DIR}/${AHEADLIBEX_DEF}")
else()
  target_link_options(${PROJECT_NAME} PRIVATE "${CMAKE_CURRENT_LIST_DIR}/${AHEADLIBEX_DEF}")
endif()
