<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Label="ProjectConfigurations">
{{PROJECT_CONFIGS}}
  </ItemGroup>
  <PropertyGroup Label="Globals">
    <VCProjectVersion>18.0</VCProjectVersion>
    <ProjectGuid>{{PROJECT_GUID}}</ProjectGuid>
    <RootNamespace>{{PROJECT_NAME}}</RootNamespace>
    <Keyword>Win32Proj</Keyword>
    <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
  </PropertyGroup>
{{CL_ITEM_GROUP}}
{{ASM_ITEM_GROUP}}
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" />
{{CONFIG_GROUPS}}
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.props" />
  <ImportGroup Label="ExtensionSettings">
{{EXTENSION_SETTINGS}}
  </ImportGroup>
  <ImportGroup Label="Shared">
  </ImportGroup>
{{PROPERTY_SHEETS}}
  <PropertyGroup Label="UserMacros" />
{{ITEM_DEFINITIONS}}
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
  <ImportGroup Label="ExtensionTargets">
{{EXTENSION_TARGETS}}
  </ImportGroup>
</Project>

<!--
generated by AheadLibEx (Rust)
Author: i1tao
Blog: https://www.winsec.cn
Github: https://github.com/i1tao/AheadLibEx
-->
