<Solution>
  <Configurations>
{{PLATFORMS}}
  </Configurations>
  <Project Path="{{PROJECT_NAME}}.vcxproj" />
</Solution>

<!--
generated by AheadLibEx (Rust)
Author: i1tao
Blog: https://www.winsec.cn
Github: https://github.com/i1tao/AheadLibEx
-->