Microsoft Visual Studio Solution File, Format Version 12.00
# generated by AheadLibEx (Rust)
# Author: i1tao
# Blog: https://www.winsec.cn
# Github: https://github.com/i1tao/AheadLibEx

VisualStudioVersion = 17.5.33530.505
MinimumVisualStudioVersion = 10.0.40219.1
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "{{PROJECT_NAME}}", "{{PROJECT_NAME}}.vcxproj", "{{PROJECT_GUID}}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|x64 = Debug|x64
		Debug|x86 = Debug|x86
		Release|x64 = Release|x64
		Release|x86 = Release|x86
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{{PROJECT_GUID}}.Debug|x64.ActiveCfg = Debug|x64
		{{PROJECT_GUID}}.Debug|x64.Build.0 = Debug|x64
		{{PROJECT_GUID}}.Debug|x86.ActiveCfg = Debug|Win32
		{{PROJECT_GUID}}.Debug|x86.Build.0 = Debug|Win32
		{{PROJECT_GUID}}.Release|x64.ActiveCfg = Release|x64
		{{PROJECT_GUID}}.Release|x64.Build.0 = Release|x64
		{{PROJECT_GUID}}.Release|x86.ActiveCfg = Release|Win32
		{{PROJECT_GUID}}.Release|x86.Build.0 = Release|Win32
	EndGlobalSection
 	GlobalSection(SolutionProperties) = preSolution
 		HideSolutionNode = FALSE 
	EndGlobalSection 
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {{SOLUTION_GUID}}
	EndGlobalSection
EndGlobal