# generated by AheadLibEx (Rust) - x64 jump table (GAS)
# Author: i1tao
# Blog: https://www.winsec.cn
# Github: https://github.com/i1tao/AheadLibEx

    .intel_syntax noprefix
    .text

{{ASM_EXTERNS}}

{{ASM_JUMPS}}

