;
; generated by AheadLibEx (Rust)
; Author:i1tao
; Blog:https://www.winsec.cn
; Github:https://github.com/i1tao/AheadLibEx

; 64-bit jump table
;
; Add the .asm file into your project.
; Right click file -> Properties -> General
; Item Type : Custom Build Tool
; Excluded From Build : No
;
; In "Custom Build Tool" Properties
; Command Line :ml64 /Fo $(IntDir)%(fileName).obj /c /Cp %(fileName).asm
; Outputs:$(IntDir)%(fileName).obj;%(Outputs)
; Link Objects:Yes

.DATA
{{ASM_EXTERNS}}
.CODE
{{ASM_JUMPS}}
END
