;
; generated by AheadLibEx (Rust) - x86 jump table (MASM)
;
; Author: i1tao
; Blog: https://www.winsec.cn
; Github: https://github.com/i1tao/AheadLibEx

.386
.model flat
option casemap:none

.code

{{ASM_JUMPS}}

END

